# Generated by Django 3.2 on 2021-04-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_bloguser_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogUser',
        ),
    ]
